### ISSUE TITLE
Change app ID

### ISSUE THREAD

**Issue by jendrikseipp** [scx/rednotebook-flatpak#1]
Could you please change the URI name from `io.sourceforge.RedNotebook` to `app.RedNotebook`? I'm not sure how long RedNotebook will use sourceforge for hosting its website. The new URL for the project is https://rednotebook.app, but I haven't advertised it anywhere, yet.

**Comment by scx** [comment]
@jendrikseipp 

> Could you please change the URI name from `io.sourceforge.RedNotebook` to `app.RedNotebook`? 

Unfortunately, a three-part form is required.

http://docs.flatpak.org/en/latest/conventions.html#application-ids
> As described in Using Flatpak, Flatpak requires each application to have a unique identifier, which has a **three-part** form such as org.gnome.Dictionary.

http://docs.flatpak.org/en/latest/using-flatpak.html#identifiers
> Flatpak identifies each application and runtime using a unique **three-part** identifier, such as com.company.App. The final segment of this address is the object’s name, and the preceding part identifies the developer, so that the same developer can have multiple applications, like com.company.App1 and com.company.App2.

https://github.com/flathub/flathub/wiki/AppData-Guidelines#id
```
<!-- Good -->
<id>org.flatpak.qtdemo</id>

<!-- Bad -->
<id>org.flatpak.qtdemo.desktop</id>
<id>qtdemo.desktop</id>

<!-- Incorrect -->
<id>qtdemo</id>
```

Of course, you can choose the one that suits you best.
If you would like to use the `rednotebook.app` domain, I suggest choosing the `app.rednotebook.RedNotebook` ID.

This form is actually quite popular on Flathub:
```
ch.openboard.OpenBoard
com.albiononline.AlbionOnline
com.anydesk.Anydesk
com.bluejeans.BlueJeans
com.dosbox.DOSBox
com.github.libresprite.LibreSprite
com.github.marktext.marktext
com.github.utsushi.Utsushi
com.makemkv.MakeMKV
com.notepadqq.Notepadqq
com.remarkable.reMarkable
com.slack.Slack
com.snes9x.Snes9x
com.stepmania.StepMania
com.teeworlds.Teeworlds
com.viber.Viber
cx.ring.Ring
fr.natron.Natron
im.gitter.Gitter
im.pidgin.Pidgin
im.riot.Riot
im.srain.Srain
info.bibletime.BibleTime
info.colobot.Colobot
io.atom.Atom
io.botfather.Botfather
io.brackets.Brackets
io.exodus.Exodus
io.github.Cockatrice.cockatrice
io.github.openWMail.openWMail
io.github.qtox.qTox
io.github.quodlibet.QuodLibet
io.gitlab.construo.construo
io.gitlab.evtest_qt.evtest_qt
io.gitlab.jstest_gtk.jstest_gtk
io.gitlab.sdl_jstest.sdl_jstest
io.mgba.mGBA
io.webtorrent.WebTorrent
net.minetest.Minetest
net.openra.OpenRA
net.pcsx2.PCSX2
net.poedit.Poedit
net.redeclipse.RedEclipse
net.runelite.RuneLite
net.scribus.Scribus
net.sourceforge.electrip.Electrip
net.supertuxkart.SuperTuxKart
net.wz2100.wz2100
org.avidemux.Avidemux
org.blender.Blender
org.bzflag.BZFlag
org.codeblocks.codeblocks
org.darktable.Darktable
org.davmail.DavMail
org.flightgear.FlightGear
org.freeciv.Freeciv
org.freefilesync.FreeFileSync
org.fritzing.Fritzing
org.gahshomar.Gahshomar
org.gajim.Gajim
org.geany.Geany
org.geogebra.GeoGebra
org.gimp.GIMP
org.gnucash.GnuCash
org.gpodder.gpodder
org.inkscape.Inkscape
org.jamovi.jamovi
org.jdownloader.JDownloader
org.keepassxc.KeePassXC
org.libreoffice.LibreOffice
org.librepcb.LibrePCB
org.megaglest.MegaGlest
org.musescore.MuseScore
org.mypaint.MyPaint
org.naev.Naev
org.nextcloud.Nextcloud
org.octave.Octave
org.openclonk.OpenClonk
org.openmw.OpenMW
org.openscad.OpenSCAD
org.openshot.OpenShot
org.openttd.OpenTTD
org.pencil2d.Pencil2D
org.photoqt.PhotoQt
org.pitivi.Pitivi
org.ppsspp.PPSSPP
org.pyzo.pyzo
org.qbittorrent.qBittorrent
org.qgis.qgis
org.qownnotes.QOwnNotes
org.remmina.Remmina
org.sauerbraten.Sauerbraten
org.scantailor.ScanTailor
org.scummvm.ScummVM
org.shotcut.Shotcut
org.signal.Signal
org.sparkleshare.SparkleShare
org.speedcrunch.SpeedCrunch
org.stellarium.Stellarium
org.texstudio.TeXstudio
org.tuxpaint.Tuxpaint
org.vim.Vim
org.wesnoth.Wesnoth
org.xiphos.Xiphos
org.xonotic.Xonotic
org.zotero.Zotero
org.zulip.Zulip
space.fips.Fips
tv.kodi.Kodi
us.zoom.Zoom
website.i2pd.i2pd
ws.openarena.OpenArena
```

The selected ID will affect filenames:
- AppData file: `${FLATPAK_ID}.appdata.xml`
- Desktop file: `${FLATPAK_ID}.desktop`
- Icon file: `${FLATPAK_ID}.png` or/and `${FLATPAK_ID}.svg`

Please let me know if `app.rednotebook.RedNotebook` suits you.

**Comment by jendrikseipp** [comment]
Thank you very much for clarifying this. I should have investigated before filing this issue. I like the ID `app.rednotebook.RedNotebook`.

**Comment by scx** [comment]
Done.
https://github.com/scx/rednotebook-flatpak/commit/5693ad1bcfbdd397783b6045f3d768355a671eac
https://github.com/scx/flathub/commit/74af44b7ec9fbd62b1c98bcf8257e994fa70a81d

**Comment by jendrikseipp** [comment]
Thanks!
