### ISSUE TITLE
Case of filenames

### ISSUE THREAD

**Issue by jendrikseipp** [scx/rednotebook-flatpak#2]
Some of the yaml files use uppercase letters (e.g., python3-PyYAML.yaml, RedNotebook.yaml), while others are all lowercase (e.g., python3-pyenchant.yaml). I think it would be good to be consistent here and use lowercase filenames everywhere. To be clear, I think we should use the name "rednotebook" in filenames. Inside the files, when referring to the application name, we should use the name "RedNotebook".

**Comment by scx** [comment]
As for the `RedNotebook`, I used the last part of the three-part ID. I wanted to be consistent with the current naming convention.
https://github.com/flathub/shared-modules/tree/91a244dd281e5825f2ddc288e10eda0c687479b8/SDL

As for `python3-PyYAML.yaml`, this file is auto-generated by a generator based on [flatpak-pip-generator](https://github.com/flatpak/flatpak-builder-tools/blob/578d88d5fa857a599bb423dbc1bc1a8e34cda9ed/pip/flatpak-pip-generator) from the [flatpak-builder-tools](https://github.com/flatpak/flatpak-builder-tools/tree/578d88d5fa857a599bb423dbc1bc1a8e34cda9ed) bundle.
In fact, this name comes from the [PyYAML](https://pypi.org/project/PyYAML) PIP module.
The same applies to [pyenchant](https://pypi.org/project/pyenchant), where everything is written in lower case.

Of course I could change this, but it would complicate the updating process.

**Comment by jendrikseipp** [comment]
Sounds good, let's leave the names as they are. Sorry for the noise, I'm still learning about the flatpak conventions :-)
